export interface RawMaterial {
  partNumber: string;
  description: string;
  category: string;
  uom: string;
}

export const RAW_MATERIALS: RawMaterial[] = [
  { partNumber: "RM-WD-TB737", description: "RM:Wood Products:Planed Pine - 4*1-13ft", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB738", description: "RM:Wood Products:Planed Pine - 5*1-13ft (115*22 mm)", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB739", description: "RM:Wood Products:Planed Pine - 5*1-13ft (128*22 mm)", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB741", description: "RM:Wood Products:Planed Pine - 6*1 13ft (146*22 mm)", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB736", description: "RM:Wood Products:Planed Pine - 3*1-13ft", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB734", description: "RM:Wood Products:Planed Pine - 7*1 13ft", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB740", description: "RM:Wood Products:Planed Pine - 5*1-13ft (131*36 mm)", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB735", description: "RM:Wood Products:Planed Pine - 2*2-13ft", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB742", description: "RM:Wood Products:Planed Pine - 6*2 13ft (146*45 mm)", category: "Timber", uom: "PCS" },
  { partNumber: "RM-WD-TB858", description: "RM:Wood Products:Pine - 6*1-13ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB857", description: "RM:Wood Products:Pine - 4*1-13ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB859", description: "RM:Wood Products:Planed Pine - 4*1-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB209", description: "RM:Wood Products:Pine - 6*2-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB203", description: "RM:Wood Products:Pine - 6*1- 7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB847", description: "RM:Wood Products:Planed Pine - 6*1-11.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB868", description: "RM:Wood Products:Pine - 6*1-11.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB211", description: "RM:Wood Products:Pine - 3*1-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB314", description: "RM:Wood Products:Pine - 6*1-9.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB863", description: "RM:Wood Products:Pine - 4*1-11.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB869", description: "RM:Wood Products:Planed Pine - 6*1-9.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB846", description: "RM:Wood Products:Planed Pine - 4*1-11.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB206", description: "RM:Wood Products:Pine - 7*1-9.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB862", description: "RM:Wood Products:Pine - 4*1-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB207", description: "RM:Wood Products:Pine - 7*1-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB313", description: "RM:Wood Products:Pine - 4*1-9.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB204", description: "RM:Wood Products:Planed Pine - 6*1-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB853", description: "RM:Wood Products:Planed Pine - 7*1 11.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB866", description: "RM:Wood Products:Planed Pine - 7*1-7.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB856", description: "RM:Wood Products:Planed Pine - 4*1-3.2 ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB845", description: "RM:Wood Products:Planed Pine - 4*1-9.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB867", description: "RM:Wood Products:Planed Pine - 7*1-9.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB028", description: "RM:Wood Products:Pine - 6*1 - 8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB743", description: "RM:Wood Products - Planed Pine - 4*1 - 8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB844", description: "RM:Wood Products:Pine - 8x1 - 12ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB718", description: "RM:Wood Products:pine - 6x1 - 12ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB716", description: "RM:Wood Products:pine - 4x1 - 12ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB311", description: "RM:Wood Products:Pine - 5x1 - 12ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB843", description: "RM:Wood Products:Pine - 10x1 - 12ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB849", description: "RM:Wood Products:Planed Pine - 5*1-11.8ft (131*36mm)", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB851", description: "RM:Wood Products:Planed Pine - 5*1 - 11.8ft (115*22)", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-TB848", description: "RM:Wood Products:Planed Pine - 6*2-11.8ft", category: "Timber", uom: "PC" },
  { partNumber: "RM-WD-BD007", description: "RM:Wood Products:Plain MDF - 3 mm", category: "MDF boards", uom: "PCS" },
  { partNumber: "RM-WD-BD008", description: "RM:Wood Products:Plain MDF - 6 mm", category: "MDF boards", uom: "PCS" },
  { partNumber: "RM-WD-BD009", description: "RM:Wood Products:Plain MDF - 9 mm", category: "MDF boards", uom: "PCS" },
  { partNumber: "RM-WD-BD005", description: "RM:Wood Products:Plain MDF - 12 mm", category: "MDF boards", uom: "PCS" },
  { partNumber: "RM-WD-BD006", description: "RM:Wood Products:Plain MDF - 18 mm", category: "MDF boards", uom: "PCS" },
  { partNumber: "RM-WD-PW002", description: "RM:Wood Products:AB Plywood - 18 mm", category: "Plywood boards", uom: "PCS" },
  { partNumber: "RM-WD-PW006", description: "Rm:sofa Materials:ab Plywood - 9 Mm", category: "Plywood boards", uom: "PC" },
  { partNumber: "RM-SF-GN041", description: "RM:Sofa Materials:Wood Glue - 20KG Bucket", category: "Wood glue", uom: "KGS" },
  { partNumber: "RM-WD-GL002", description: "RM:Wood Products:Wood Glue Professional - 4KG Bucket", category: "Wood glue", uom: "KGS" },
  { partNumber: "RM-WD-AC113", description: "RM:Wood Products:Brad Nails 30 mm", category: "Pins/staples/door catch", uom: "PKTS" },
  { partNumber: "RM-SF-AC006", description: "RM:Sofa Materials:Staples 8010", category: "Pins/staples/door catch", uom: "PKTS" },
  { partNumber: "RM-SF-AC109", description: "RM:Wood Products:Staples K416", category: "Pins/staples/door catch", uom: "PKTS" },
  { partNumber: "RM-WD-AC019", description: "RM:Wood Products:Double Roller Catch", category: "Pins/staples/door catch", uom: "PKTS" },
  { partNumber: "RM-SF-AC005", description: "Rm:sofa Materials:staples- 9010", category: "Pins/staples/door catch", uom: "PKT" },
  { partNumber: "RM-SF-SC004", description: "RM:Sofa Materials:Screw 4*40 mm", category: "Screws", uom: "PKTS" },
  { partNumber: "RM-SF-SC005", description: "RM:Sofa Materials:Screw 4*50 mm", category: "Screws", uom: "PKTS" },
  { partNumber: "RM-SF-SC010", description: "RM:Sofa Materials:Screw 5*75 mm", category: "Screws", uom: "PKTS" },
  { partNumber: "RM-SF-SC002", description: "RM:Sofa Materials:Screw 3*16 mm", category: "Screws", uom: "PKTS" },
  { partNumber: "FP-WB-SW001", description: "FP:Webbing:Webbing Standard Strength", category: "Standard Webbing", uom: "M" },
  { partNumber: "RM-WD-HI001", description: "RM:Wood Products:Butt Hinge (Brass) 1.5\"", category: "Hinges", uom: "PKTS" },
  { partNumber: "RM-WD-CM016", description: "RM:Wood Products:Body Filler - 4.7KG", category: "Coating material", uom: "KGS" },
  { partNumber: "RM-WD-CM017", description: "RM:Wood Products:Body Filler Hardener - 80 Grams", category: "Coating material", uom: "GRAMS" },
  { partNumber: "RM-WD-CM015", description: "RM:Wood Products:Spot Putty - 4KG", category: "Coating material", uom: "KGS" },
  { partNumber: "RM-SF-CM002", description: "RM:Sofa Materials:sanding sealer", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM014", description: "RM:Wood Products:Glory Primer White NC - 4L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM042", description: "RM:Sofa Materials:Glory Thinner Standard - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM041", description: "RM:Wood Products:Glory Mahogany Brown 50% NC - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM038", description: "RM:Wood Products:Glory Glouchester Brown 50% NC - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM034", description: "RM:Wood Products:Glory Black Night 50% NC - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM040", description: "RM:Wood Products:Glory Hush White 50% NC - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM007", description: "RM:Wood Products:Glory Earthy Red 50% 1K", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM049", description: "RM:Wood Products:Glory Autocryl Hardener - 1L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM065", description: "RM:Wood Products:Glory Cedar 50% NC - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM046", description: "RM:Wood Products:Glory Autocryl Hush White - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM048", description: "RM:Wood Products:Glory Autocryl Black Night - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM045", description: "RM:Wood Products:Glory Autocryl Mahogany Brown - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM047", description: "RM:Wood Products:Glory Autocryl Cedar - 20L", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-CM058", description: "RM:Wood Products:Corrugated Carton 2 Ply", category: "Coating material", uom: "KGS" },
  { partNumber: "RM-WD-CM019", description: "Rm:wood Products:glory Clear Varnish Matte - Nitrocellulose", category: "Coating material", uom: "L" },
  { partNumber: "RM-WD-SP001", description: "RM:Wood Products:Sandpaper P120 - 25M Roll", category: "Sand paper", uom: "M" },
  { partNumber: "RM-WD-SP002", description: "RM:Wood Products:Sandpaper P180 - 50M Roll", category: "Sand paper", uom: "M" },
  { partNumber: "RM-WD-SP003", description: "RM:Wood Products:Sandpaper P240 - 100 Sheets Pack", category: "Sand paper", uom: "PKTS" },
  { partNumber: "RM-WD-SP004", description: "Rm:wood Products:sandpaper P80", category: "Sand paper", uom: "M" },
  { partNumber: "RM-WD-LT001", description: "RM:Wood Products:Low Friction Tape", category: "Friction tape", uom: "M" },
  { partNumber: "RM-WD-FT016", description: "RM:Wood Products:Bolt M6 Hex 4\"", category: "Fasterners", uom: "PCS" },
  { partNumber: "RM-WD-FT017", description: "RM:Wood Products:Washer M6", category: "Fasterners", uom: "PCS" },
  { partNumber: "RM-WD-FT018", description: "RM:Wood Products:Wing Nut M6", category: "Fasterners", uom: "PCS" },
  { partNumber: "SS-CN-CN340", description: "SS:P80 1370x2150mm Sanding Belt (Paper Back)", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN023", description: "Ss:dust Masks", category: "Consumable", uom: "PKT" },
  { partNumber: "SS-CN-CN113", description: "Ss:surgical Gloves", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN140", description: "SS:Malpha Bits D35mm", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN341", description: "SS:P120 1370x2150mm Sanding Belt (Paper Back)", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN046", description: "Ss:jumbo Tissues", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN051", description: "Ss:liquid Soap", category: "Consumable", uom: "L" },
  { partNumber: "SS-CN-CN117", description: "Ss:thermal Paper Roll (25*50)", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN089", description: "Ss:rechargeable Aa Battery", category: "Consumable", uom: "PC" },
  { partNumber: "SS-MP-MP149", description: "Ss:needle Dv*59 180/24", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN019", description: "Ss:diamond Woolen Gloves", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN096", description: "Ss:safety Goggles (Ear Arms)", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN025", description: "Ss:ear Plugs", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN395", description: "SS:Sanding Belt 100*610mm- P80", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN092", description: "Ss:reflector Jacket (Green)", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN108", description: "Ss:stain Remover", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN204", description: "SS:Air fresheners", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN208", description: "SS:Scouring powder", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN015", description: "Ss:cooking Oil", category: "Consumable", uom: "L" },
  { partNumber: "SS-MP-MP220", description: "Band Saw Blade Sofa (30ml)", category: "Consumable", uom: "PC" },
  { partNumber: "SS-SH-SH001", description: "Ss:safety Helmet", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN011", description: "Ss:brush 3\"", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN115", description: "SS:Tape Measure 5M", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN379", description: "SS: Adhesive Tape", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN010", description: "Ss:brooms", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN121", description: "Ss:top Plugs 13A", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN124", description: "Ss:twin Sockets", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN072", description: "Ss:printing Papers", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN007", description: "Ss:bar Soap", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN209", description: "SS:Naphthalene Balls", category: "Consumable", uom: "PKT" },
  { partNumber: "SS-CN-CN123", description: "Ss:twin Facepiece Respirator", category: "Consumable", uom: "PC" },
  { partNumber: "SS-CN-CN039", description: "Ss:handwash", category: "Consumable", uom: "L" },
  { partNumber: "SS-EL-EL004", description: "Ss:4 Way Extension Tlac", category: "Consumable", uom: "PC" },
  { partNumber: "SS-MC-MC142", description: "SS: Hex head self drilling screws 1.25 inch", category: "Consumable", uom: "PKT" },
  { partNumber: "SS-MC-MC141", description: "hex head self drilling screws 1.5 inch", category: "Consumable", uom: "PKT" },
  { partNumber: "SS-TL-TL19", description: "SS:CEO SCISSOR No 10", category: "Consumable", uom: "PC" },
  { partNumber: "SS-EL-EL005", description: "Ss:6 Way Extension Tlac", category: "Consumable", uom: "PC" },
  { partNumber: "FP-RL-PU008", description: "Fp:rolls:pu:plain Matte:cream", category: "Consumable", uom: "M" },
  { partNumber: "FP-FI-FF101", description: "FP:Fibre: Comfort Fibre - 4kg", category: "Consumable", uom: "KG" },
  { partNumber: "FP-FM-FC005", description: "Fp:foam:5Kg Packing Multi Colored Foam Chips::", category: "Consumable", uom: "KG" },
  { partNumber: "RM-MT-CT001", description: "RM:Mattresses:Cellotape", category: "Consumable", uom: "PC" }
];
